### ISSUE TITLE
THE APP ICON

### ISSUE THREAD

**Issue by Abdallah-Moh** [PhotostatEditor/Photostat#15]
as @Suzie97 said 
> If anyone wants to provide ideas, make sure to follow the elementary HIG.
https://docs.elementary.io/hig/reference/iconography

**Comment by Suzie97** [comment]
If anyone wants to provide ideas, make sure to follow the elementary HIG.
 https://docs.elementary.io/hig/reference/iconography

**Comment by Suzie97** [comment]
![Photostat Flower](https://user-images.githubusercontent.com/68198116/122723530-b47ac380-d290-11eb-86b1-007219293055.png)

I'll add a pencil or paint brush to this diagonally.

**Comment by Abdallah-Moh** [comment]
It does not need use the white one

**Comment by Suzie97** [comment]
> 
> 
> It does not need use the white one

If we don't use a pencil or pen, it will feel like a photos app because the colors are inspired by apple photos and google photos and literally every other photo app.

**Comment by Abdallah-Moh** [comment]
ok

**Comment by Suzie97** [comment]
![App Icon](https://user-images.githubusercontent.com/68198116/122879044-0fc2b980-d356-11eb-8861-c913be417e3e.png)

@syfds , @Abdallah-Moh what do you think?

**Comment by Suzie97** [comment]
![App Icon _ 128](https://user-images.githubusercontent.com/68198116/122879545-a42d1c00-d356-11eb-8df5-49bedbccef4c.png)

Experimenting with a darker background to match with the app.

**Comment by Abdallah-Moh** [comment]
shadow does not match

**Comment by Abdallah-Moh** [comment]
shadow does not match

**Comment by syfds** [comment]
In the dark variant the pencil should be probably white at the end. To be honest I like the version without pencil 🤔

**Comment by Abdallah-Moh** [comment]
I agree I told @Suzie97 but he said that it will look like a photos app

**Comment by Suzie97** [comment]
![Screenshot from 2021-06-23 06-38-14](https://user-images.githubusercontent.com/68198116/123019384-008f4a80-d3ee-11eb-96a6-b0bdcc6e5f6e.png)

![Screenshot from 2021-06-23 06-40-17](https://user-images.githubusercontent.com/68198116/123019396-038a3b00-d3ee-11eb-8174-da2e3dbc3617.png)

![Screenshot from 2021-06-23 06-38-41](https://user-images.githubusercontent.com/68198116/123019398-05ec9500-d3ee-11eb-93af-9c7f25647952.png)

These are the icons for apple photos, google photos and GNOME photos respectively. A common pattern can be observed between these icons i.e. a ring of elements with similar colors. So I took inspiration from that pattern and made the flower style icon for Photostat.

I added the pencil icon because Photostat is primarily a photo editing application. So I wanted to portray that inside the icon itself.

If we use only the flower pattern, I can almost a guarantee that a lot of users will just think it is Apple Photos or Google Photos.

Also, the pencil icon is generally used in other elementary icons to indicate that something can be edited. Here are some example:

![Screenshot from 2021-06-23 06-57-20](https://user-images.githubusercontent.com/68198116/123020669-49e09980-d3f0-11eb-85ad-b93dab4d3616.png)

There are the latest revisions to the icons. I removed the transperancy effect from the smaller icons to improve readibility and contrast.

![Screenshot from 2021-06-23 07-03-00](https://user-images.githubusercontent.com/68198116/123021153-2bc76900-d3f1-11eb-8c1f-0ab2202d2124.png)

And these are the bigger 128px and 64px icons.

![Screenshot from 2021-06-23 07-03-08](https://user-images.githubusercontent.com/68198116/123021120-1baf8980-d3f1-11eb-884f-f6a9f853e831.png)

PS Personally, I also like the version without the pencil. But I'm kind of stuck in a dilemma right now.

**Comment by Suzie97** [comment]
Just adding the glimpse icon here to show how well it demonstrates photo editing in a 128px box.

![Screenshot from 2021-06-23 07-06-50](https://user-images.githubusercontent.com/68198116/123021447-c3c55280-d3f1-11eb-8ecd-c882387ef59b.png)

**Comment by Suzie97** [comment]
Even more revisions, this time I've used the elementary stylesheet colors. I think it was a good choice. The contrast is much better. So far, I've only worked on the 128 px icon.

## Solid Colors
![Solid Color Photostat Icon](https://user-images.githubusercontent.com/68198116/123280141-291a6000-d526-11eb-99a2-1c7a0dba6cfc.png)

## Translucent Colors
![90% Transperant Photostat Icon](https://user-images.githubusercontent.com/68198116/123280283-4a7b4c00-d526-11eb-8f49-e3b9007b183c.png)

## Bigger Version
This is the icons zoomed in so you can see the details
![Screenshot from 2021-06-24 19-58-00](https://user-images.githubusercontent.com/68198116/123280608-8d3d2400-d526-11eb-99d6-4ad625e70e45.png)

@Abdallah-Moh, can you help me a little with the icons? I want the orange petal to be above the yellow petal and below the red petal so the patter is not broked. But I can't find a way to do that. :-/

**Comment by Abdallah-Moh** [comment]
OK is the svg on figma

**Comment by Suzie97** [comment]
> OK is the svg on figma

yes

**Comment by Abdallah-Moh** [comment]
Ok

**Comment by Abdallah-Moh** [comment]
Are the petal grouped with the dark semi transparent petal behind it

**Comment by Abdallah-Moh** [comment]
Now?

**Comment by Abdallah-Moh** [comment]
It will be impossible you will have to increase one more petal or decrease

**Comment by Abdallah-Moh** [comment]
@Suzie97 The icon is ready let's use it

**Comment by Suzie97** [comment]
@Abdallah-Moh, there are some small detail improvements I want to try, like using a glass type material, do some more adjustments to the lighting and other things.

**Comment by Suzie97** [comment]
![Photostat Glass 1](https://user-images.githubusercontent.com/68198116/124119706-76e81880-da90-11eb-9677-7731c856dabf.png)

![App Icon _ 134](https://user-images.githubusercontent.com/68198116/124119743-80718080-da90-11eb-9290-b86ac7ea6d05.png)

@Abdallah-Moh , @syfds choose one, we'll use it 😀️

**Comment by syfds** [comment]
@Suzie97 , I like the second one! :-)

**Comment by Abdallah-Moh** [comment]
Let's use the second
