### ISSUE TITLE
Enhanced and Modern Design

### ISSUE THREAD

**Issue by JeysonFlores** [PhotostatEditor/Photostat#39]
## Problem

Hello, I just discovered this project and I'd like to help you guys with the design part. In my opinion this might be the next big project that comes from eOS ecosystem so I have some proposal designs that if you agree in a couple of days I could write them.
## Proposal
These are the changes I'd like you to consider:
 - Cut the headerbar into 4 pieces one for each panel of the window to give more emphasis to each panel and also make this segmented headerbar a plainer looking.
 - A pretty basic draft of the toolbar
 - Usage of some open source icon packs (There are really good-looking icon packs which are open source and free of use, I'm using some of them in a eOS app I'm writing right now so a lot of icon packs come to my mind)

If you agree let me know to start working on them!

**Comment by Suzie97** [comment]
@JeysonFlores thank you so much for your interest in the project.

As for icons, we need to make sure that they follow the elementary guidelines and look cohesive with the system.

And I am not quite convinced with the full height panels (if that is what you mean). I think the headerbar acts as a nice anchor, with the most used tools. Currently, we want the headerbar to be an extension of the main UI rather than a part of it. So we are planning to change the content of the headerbar depending on the context. 

You can join in the discussion over here: https://github.com/PhotostatEditor/Photostat/issues/4.

![image](https://user-images.githubusercontent.com/68198116/132690162-e17c0aed-9f19-4ffc-b903-35507e483b42.png)

This is the basic layout that we are planning to implement. We have the toolbar on the left, with the tool properties attached to it. The main canvas area in the middle, and the layers and history manager towards the right. We'll also make the panes interchangeable. 

There can be a drop down arrow near the document title in the headerbar. Clicking on that will popup the document properties.

I am closing this issue because I think the scope is too big to be handled in one issue and it would be better to discuss about the individual elements in their own issue. 

PS You can check out the figma design here https://www.figma.com/file/3H1lH0CfR2Tz5I9dvGJaBg/Photostat?node-id=0%3A1

**Comment by JeysonFlores** [comment]
Oh I get it. I didn't check if you already had a specified design. Thanks for reading my proposal!
